import type { DemoBooking, DemoOrder } from "@/lib/storefront-types";

const now = Date.now();
const ago = (days: number) => new Date(now - days * 86_400_000).toISOString();
const ahead = (days: number) => new Date(now + days * 86_400_000).toISOString();

export const demoHistoryOrders: DemoOrder[] = [
  {
    id: "ord_demo_shipped",
    number: "YR-2026-DM1201",
    createdAt: ago(2),
    updatedAt: ago(0.2),
    status: "shipped",
    paymentStatus: "paid",
    paymentMethod: "virtual_account",
    paymentExpiresAt: null,
    fulfillmentStatus: "shipped",
    deliveryMethod: "regular",
    courier: "JNE",
    trackingNumber: "JNE-YORU-882013",
    estimatedDeliveryAt: ahead(1),
    refundStatus: "none",
    disputeStatus: "none",
    cancellationReason: null,
    subtotalMinor: 37800000,
    shippingMinor: 1800000,
    serviceFeeMinor: 200000,
    discountMinor: 0,
    totalMinor: 39800000,
    address: {
      recipientName: "Customer Demo",
      phone: "081234567890",
      addressLine: "Jl. Melati No. 18",
      city: "Jakarta Selatan",
      postalCode: "12190",
      notes: "Titip ke resepsionis bila tidak ada orang.",
    },
    items: [
      {
        lineId: "line_demo_serum",
        productId: "prd_glow_reset",
        variantId: "var_serum_20",
        quantity: 2,
      },
    ],
    timeline: [
      {
        label: "Pesanan dibuat",
        detail: "Pesanan diterima sistem Yoru.",
        occurredAt: ago(2),
        completed: true,
      },
      {
        label: "Pembayaran berhasil",
        detail: "Virtual account telah terverifikasi.",
        occurredAt: ago(2),
        completed: true,
      },
      {
        label: "Dikemas partner",
        detail: "Partner menyelesaikan pengepakan.",
        occurredAt: ago(1.4),
        completed: true,
      },
      {
        label: "Dalam pengiriman",
        detail: "Paket diserahkan ke JNE.",
        occurredAt: ago(0.2),
        completed: true,
      },
      {
        label: "Diterima customer",
        detail: "Menunggu konfirmasi penerimaan.",
        occurredAt: ahead(1),
        completed: false,
      },
    ],
  },
  {
    id: "ord_demo_pending",
    number: "YR-2026-DM1202",
    createdAt: ago(0.1),
    updatedAt: ago(0.1),
    status: "awaiting_payment",
    paymentStatus: "pending",
    paymentMethod: "ewallet",
    paymentExpiresAt: ahead(0.25),
    fulfillmentStatus: "unfulfilled",
    deliveryMethod: "express",
    courier: null,
    trackingNumber: null,
    estimatedDeliveryAt: null,
    refundStatus: "none",
    disputeStatus: "none",
    cancellationReason: null,
    subtotalMinor: 27900000,
    shippingMinor: 3500000,
    serviceFeeMinor: 200000,
    discountMinor: 0,
    totalMinor: 31600000,
    address: {
      recipientName: "Customer Demo",
      phone: "081234567890",
      addressLine: "Jl. Melati No. 18",
      city: "Jakarta Selatan",
      postalCode: "12190",
    },
    items: [
      {
        lineId: "line_demo_tote",
        productId: "prd_satin_tote",
        variantId: "var_tote_ink",
        quantity: 1,
      },
    ],
    timeline: [
      {
        label: "Pesanan dibuat",
        detail: "Menunggu penyelesaian pembayaran.",
        occurredAt: ago(0.1),
        completed: true,
      },
      {
        label: "Pembayaran berhasil",
        detail: "Belum terverifikasi.",
        occurredAt: ahead(0.25),
        completed: false,
      },
      {
        label: "Diproses partner",
        detail: "Dimulai setelah pembayaran berhasil.",
        occurredAt: ahead(0.5),
        completed: false,
      },
    ],
  },
];

export const demoHistoryBookings: DemoBooking[] = [
  {
    id: "bkg_demo_confirmed",
    number: "YB-2026-DM2201",
    createdAt: ago(1),
    updatedAt: ago(0.1),
    status: "assigned",
    paymentStatus: "paid",
    paymentMethod: "card",
    paymentExpiresAt: null,
    refundStatus: "none",
    cancellationReason: null,
    rescheduleCount: 0,
    serviceId: "svc_home_facial",
    serviceName: "Home Facial Reset",
    scheduledAt: ahead(1),
    professionalId: "pro_nadia",
    professionalName: "Nadia Rahma",
    address: {
      recipientName: "Customer Demo",
      phone: "081234567890",
      addressLine: "Jl. Melati No. 18",
      city: "Jakarta Selatan",
      postalCode: "12190",
      notes: "Hubungi saat tiba di gerbang.",
    },
    notes: "Fokus hidrasi dan skin barrier.",
    serviceSubtotalMinor: 34900000,
    transportMinor: 2000000,
    platformFeeMinor: 500000,
    totalMinor: 37400000,
    otp: "4821",
    timeline: [
      {
        label: "Booking dibuat",
        detail: "Slot layanan berhasil dikunci.",
        occurredAt: ago(1),
        completed: true,
      },
      {
        label: "Pembayaran berhasil",
        detail: "Pembayaran kartu telah terverifikasi.",
        occurredAt: ago(1),
        completed: true,
      },
      {
        label: "Profesional ditugaskan",
        detail: "Nadia Rahma dikonfirmasi.",
        occurredAt: ago(0.1),
        completed: true,
      },
      {
        label: "Profesional menuju lokasi",
        detail: "Tracking aktif pada hari layanan.",
        occurredAt: ahead(0.9),
        completed: false,
      },
    ],
  },
];
