import type { Product, Service } from "@/lib/storefront-types";

export const products: Product[] = [
  {
    id: "prd_glow_reset",
    slug: "glow-reset-serum",
    name: "Glow Reset Serum",
    category: "Skincare",
    partner: "Luma Skin Studio",
    partnerLocation: "Jakarta Selatan",
    image: "/yoru-media/demo/product-serum.png",
    priceMinor: 18900000,
    compareAtMinor: 22900000,
    rating: 4.9,
    reviewCount: 328,
    badge: "Best seller",
    description:
      "Serum ringan untuk membantu merawat tampilan kulit kusam, menjaga hidrasi, dan memperkuat skin barrier.",
    highlights: [
      "Niacinamide dan panthenol",
      "Tekstur cepat menyerap",
      "Dermatologically tested",
      "Cocok untuk rutinitas pagi dan malam",
    ],
    variants: [
      { id: "var_serum_20", name: "20 ml", sku: "LUMA-GRS-20", priceMinor: 18900000, stock: 42 },
      { id: "var_serum_40", name: "40 ml", sku: "LUMA-GRS-40", priceMinor: 31900000, stock: 18 },
    ],
    shippingEta: "Tiba 1–3 hari",
    tags: ["serum", "brightening", "barrier"],
  },
  {
    id: "prd_barrier_cloud",
    slug: "barrier-cloud-moisturizer",
    name: "Barrier Cloud Moisturizer",
    category: "Skincare",
    partner: "Luma Skin Studio",
    partnerLocation: "Jakarta Selatan",
    image: "/yoru-media/demo/product-moisturizer.png",
    priceMinor: 22900000,
    rating: 4.8,
    reviewCount: 214,
    badge: "Skin barrier",
    description:
      "Moisturizer dengan tekstur cloud-gel yang memberi rasa nyaman tanpa meninggalkan sensasi berat.",
    highlights: ["Ceramide complex", "Fragrance free", "Nyaman untuk kulit sensitif", "Kemasan refillable"],
    variants: [
      { id: "var_cloud_50", name: "50 g", sku: "LUMA-BCM-50", priceMinor: 22900000, stock: 31 },
    ],
    shippingEta: "Tiba 1–3 hari",
    tags: ["moisturizer", "ceramide", "sensitive"],
  },
  {
    id: "prd_silk_repair",
    slug: "silk-repair-hair-mask",
    name: "Silk Repair Hair Mask",
    category: "Hair care",
    partner: "Atelier Hair Lab",
    partnerLocation: "Bandung",
    image: "/yoru-media/demo/product-hair-mask.png",
    priceMinor: 14900000,
    compareAtMinor: 17900000,
    rating: 4.7,
    reviewCount: 186,
    badge: "Salon finish",
    description:
      "Masker rambut intensif untuk rambut kering, sering di-styling, dan membutuhkan kelembutan ekstra.",
    highlights: ["Hydrolyzed protein", "Bebas mineral oil", "Aroma lembut", "Hasil terasa setelah 10 menit"],
    variants: [
      { id: "var_mask_180", name: "180 g", sku: "AHL-SRM-180", priceMinor: 14900000, stock: 55 },
    ],
    shippingEta: "Tiba 2–4 hari",
    tags: ["hair mask", "repair", "salon"],
  },
  {
    id: "prd_satin_tote",
    slug: "everyday-satin-tote",
    name: "Everyday Satin Tote",
    category: "Fashion",
    partner: "Nara Objects",
    partnerLocation: "Yogyakarta",
    image: "/yoru-media/demo/product-tote.png",
    priceMinor: 27900000,
    rating: 4.9,
    reviewCount: 92,
    badge: "Limited drop",
    description:
      "Tote berstruktur lembut dengan finishing satin matte untuk kebutuhan kerja, kampus, dan agenda akhir pekan.",
    highlights: ["Kompartemen laptop 14 inci", "Inner pocket beritsleting", "Tali bahu lebar", "Material mudah dibersihkan"],
    variants: [
      { id: "var_tote_ink", name: "Ink black", sku: "NARA-EST-INK", priceMinor: 27900000, stock: 12 },
      { id: "var_tote_olive", name: "Soft olive", sku: "NARA-EST-OLV", priceMinor: 27900000, stock: 9 },
    ],
    shippingEta: "Tiba 2–5 hari",
    tags: ["bag", "tote", "fashion"],
  },
  {
    id: "prd_sun_stick",
    slug: "mineral-sun-stick",
    name: "Mineral Sun Stick SPF 50",
    category: "Skincare",
    partner: "Serein Lab",
    partnerLocation: "Surabaya",
    image: "/yoru-media/demo/product-sunstick.png",
    priceMinor: 13900000,
    rating: 4.6,
    reviewCount: 301,
    badge: "Travel ready",
    description:
      "Sun stick praktis untuk re-apply, dengan hasil natural dan nyaman digunakan di atas makeup.",
    highlights: ["SPF 50 PA++++", "Pocket size", "Tidak lengket", "Mudah digunakan ulang"],
    variants: [
      { id: "var_sun_18", name: "18 g", sku: "SER-MSS-18", priceMinor: 13900000, stock: 64 },
    ],
    shippingEta: "Tiba 1–3 hari",
    tags: ["sunscreen", "spf", "travel"],
  },
  {
    id: "prd_lip_tint",
    slug: "midnight-lip-tint",
    name: "Midnight Lip Tint",
    category: "Makeup",
    partner: "Noir Beauty",
    partnerLocation: "Tangerang",
    image: "/yoru-media/demo/product-lip-tint.png",
    priceMinor: 9900000,
    rating: 4.8,
    reviewCount: 514,
    badge: "New shades",
    description:
      "Lip tint dengan warna buildable dan stain yang tetap nyaman untuk aktivitas sehari-hari.",
    highlights: ["Buildable pigment", "Soft blur finish", "Tidak membuat bibir terasa kering", "Enam pilihan warna"],
    variants: [
      { id: "var_lip_rose", name: "After Rose", sku: "NOIR-MLT-ROS", priceMinor: 9900000, stock: 33 },
      { id: "var_lip_fig", name: "Deep Fig", sku: "NOIR-MLT-FIG", priceMinor: 9900000, stock: 27 },
      { id: "var_lip_tea", name: "Brick Tea", sku: "NOIR-MLT-TEA", priceMinor: 9900000, stock: 21 },
    ],
    shippingEta: "Tiba 1–3 hari",
    tags: ["lip tint", "makeup", "color"],
  },
];

export const services: Service[] = [
  {
    id: "svc_home_facial",
    slug: "home-facial-reset",
    name: "Home Facial Reset",
    category: "Facial",
    partner: "Luma Skin Studio",
    image: "/yoru-media/demo/service-facial.webp",
    priceMinor: 34900000,
    durationMin: 90,
    rating: 4.9,
    reviewCount: 442,
    badge: "Most booked",
    description:
      "Facial lengkap di rumah dengan konsultasi singkat, cleansing, gentle extraction, hydration, dan aftercare.",
    includes: ["Konsultasi kondisi kulit", "Double cleansing dan exfoliation", "Gentle extraction sesuai kebutuhan", "Hydrating mask dan finishing routine"],
    serviceArea: "Jakarta Selatan, Jakarta Pusat, dan Depok",
    professionals: [
      { id: "pro_nadia", name: "Nadia Rahma", title: "Senior aesthetician", rating: 4.9, completedJobs: 684, avatar: "NR" },
      { id: "pro_ayla", name: "Ayla Putri", title: "Skin therapist", rating: 4.8, completedJobs: 438, avatar: "AP" },
    ],
    tags: ["facial", "home treatment", "skin"],
  },
  {
    id: "svc_hair_spa",
    slug: "hair-spa-home",
    name: "Hair Spa at Home",
    category: "Hair",
    partner: "Atelier Hair Lab",
    image: "/yoru-media/demo/service-hair.webp",
    priceMinor: 28900000,
    durationMin: 75,
    rating: 4.8,
    reviewCount: 318,
    badge: "Relax at home",
    description:
      "Perawatan rambut dan kulit kepala di rumah, lengkap dengan pijat ringan dan blow dry natural.",
    includes: ["Scalp consultation", "Hair wash portable setup", "Treatment mask dan massage", "Natural blow dry"],
    serviceArea: "Bandung Kota dan Cimahi",
    professionals: [
      { id: "pro_raka", name: "Raka Pradana", title: "Hair therapist", rating: 4.8, completedJobs: 512, avatar: "RP" },
      { id: "pro_laras", name: "Laras Wening", title: "Hair stylist", rating: 4.9, completedJobs: 367, avatar: "LW" },
    ],
    tags: ["hair spa", "scalp", "home salon"],
  },
  {
    id: "svc_makeup_event",
    slug: "makeup-event-home",
    name: "Event Makeup at Home",
    category: "Makeup",
    partner: "Noir Beauty",
    image: "/yoru-media/demo/service-makeup.webp",
    priceMinor: 49900000,
    durationMin: 120,
    rating: 4.9,
    reviewCount: 227,
    badge: "Event ready",
    description:
      "Makeup artist datang ke lokasi untuk wisuda, pesta, lamaran, atau agenda formal lainnya.",
    includes: ["Brief look sebelum hari H", "Complexion dan eye makeup", "Basic hair styling", "Touch-up kit mini"],
    serviceArea: "Jabodetabek",
    professionals: [
      { id: "pro_meira", name: "Meira Anjani", title: "Professional makeup artist", rating: 4.9, completedJobs: 298, avatar: "MA" },
      { id: "pro_sasha", name: "Sasha Nirmala", title: "Beauty artist", rating: 4.8, completedJobs: 206, avatar: "SN" },
    ],
    tags: ["makeup", "event", "mua"],
  },
  {
    id: "svc_men_grooming",
    slug: "men-grooming-home",
    name: "Men Grooming Home Visit",
    category: "Grooming",
    partner: "Northside Grooming",
    image: "/yoru-media/demo/service-grooming.webp",
    priceMinor: 17900000,
    durationMin: 60,
    rating: 4.7,
    reviewCount: 193,
    badge: "Fast booking",
    description:
      "Haircut dan grooming profesional dengan peralatan steril yang dibawa langsung ke rumah.",
    includes: ["Style consultation", "Haircut", "Neck cleanup", "Hair styling"],
    serviceArea: "Jakarta, Bekasi, dan Tangerang",
    professionals: [
      { id: "pro_dimas", name: "Dimas Arga", title: "Senior barber", rating: 4.8, completedJobs: 741, avatar: "DA" },
    ],
    tags: ["barber", "haircut", "grooming"],
  },
  {
    id: "svc_nail_care",
    slug: "nail-care-home",
    name: "Essential Nail Care",
    category: "Nail",
    partner: "Mori Nail Room",
    image: "/yoru-media/demo/service-nail.webp",
    priceMinor: 22900000,
    durationMin: 75,
    rating: 4.8,
    reviewCount: 156,
    description:
      "Manicure dan basic gel polish di rumah dengan alat steril dan pilihan warna curated.",
    includes: ["Nail shaping", "Cuticle care", "Basic gel color", "Hand massage"],
    serviceArea: "Jakarta Selatan dan Tangerang Selatan",
    professionals: [
      { id: "pro_citra", name: "Citra Maharani", title: "Nail artist", rating: 4.8, completedJobs: 312, avatar: "CM" },
    ],
    tags: ["nail", "manicure", "home treatment"],
  },
  {
    id: "svc_hijab_style",
    slug: "hijab-styling-home",
    name: "Hijab Styling Home Visit",
    category: "Styling",
    partner: "Nara Styling",
    image: "/yoru-media/demo/service-hijab.webp",
    priceMinor: 19900000,
    durationMin: 60,
    rating: 4.9,
    reviewCount: 118,
    badge: "Occasion styling",
    description:
      "Styling hijab personal untuk wisuda, lamaran, pesta, dan kebutuhan konten.",
    includes: ["Look consultation", "Hijab styling", "Pin dan inner basic", "Foto hasil akhir"],
    serviceArea: "Yogyakarta dan Sleman",
    professionals: [
      { id: "pro_salsha", name: "Salsha Kirana", title: "Hijab stylist", rating: 4.9, completedJobs: 244, avatar: "SK" },
    ],
    tags: ["hijab", "styling", "event"],
  },
];

export const productCategories = ["Semua", ...new Set(products.map((product) => product.category))];
export const serviceCategories = ["Semua", ...new Set(services.map((service) => service.category))];
