"""Add ledger, settlement, refund, payout, reconciliation, and dispute tables.
Revision ID: 20260801_0007
Revises: 20260801_0006
"""
import uuid
from collections.abc import Sequence
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op
revision='20260801_0007'; down_revision='20260801_0006'; branch_labels=None; depends_on=None
PERMISSIONS=(("6a6098a1-d986-4b13-9c48-000000000051","finance.balance.read"),("6a6098a1-d986-4b13-9c48-000000000052","finance.payout.create"),("6a6098a1-d986-4b13-9c48-000000000053","finance.dispute.respond"),("6a6098a1-d986-4b13-9c48-000000000054","platform.finance.read"),("6a6098a1-d986-4b13-9c48-000000000055","platform.finance.manage"),("6a6098a1-d986-4b13-9c48-000000000056","platform.finance.reconcile"))
def perm(i,c): op.execute(sa.text('INSERT INTO permissions (id,code) VALUES (:i,:c) ON CONFLICT (code) DO NOTHING').bindparams(sa.bindparam('i',value=uuid.UUID(i),type_=postgresql.UUID(as_uuid=True)),c=c))
def grant(r,c): op.execute(sa.text('INSERT INTO role_permissions (role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code=:r AND p.code=:c ON CONFLICT DO NOTHING').bindparams(r=r,c=c))
def partner_rls(table):
 op.execute(sa.text(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY'));op.execute(sa.text(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY'))
 expr=f"current_setting('app.is_platform_admin',true)='true' OR COALESCE(current_setting('app.user_id',true),'')='' OR EXISTS (SELECT 1 FROM partner_memberships m WHERE m.partner_id={table}.partner_id AND m.user_id=NULLIF(current_setting('app.user_id',true),'')::uuid AND m.status='active')"
 op.execute(sa.text(f'CREATE POLICY {table}_partner_scope ON {table} FOR ALL USING ({expr}) WITH CHECK ({expr})'))
def customer_partner_rls(table):
 op.execute(sa.text(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY'));op.execute(sa.text(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY'))
 expr=f"current_setting('app.is_platform_admin',true)='true' OR {table}.customer_id=NULLIF(current_setting('app.user_id',true),'')::uuid OR EXISTS (SELECT 1 FROM partner_memberships m WHERE m.partner_id={table}.partner_id AND m.user_id=NULLIF(current_setting('app.user_id',true),'')::uuid AND m.status='active')"
 op.execute(sa.text(f'CREATE POLICY {table}_scope ON {table} FOR ALL USING ({expr}) WITH CHECK ({expr})'))
def upgrade():
 op.create_table('ledger_accounts',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('code',sa.String(180),nullable=False,unique=True),sa.Column('owner_type',sa.String(20),nullable=False),sa.Column('owner_id',postgresql.UUID(as_uuid=True)),sa.Column('account_type',sa.String(20),nullable=False),sa.Column('purpose',sa.String(50),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('status',sa.String(20),server_default='active',nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.CheckConstraint("account_type IN ('asset','liability','revenue','expense','equity')",name='ck_ledger_accounts_type'))
 op.create_table('partner_balances',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('partner_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('partners.id',ondelete='CASCADE'),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('pending_amount',sa.BigInteger(),server_default='0',nullable=False),sa.Column('available_amount',sa.BigInteger(),server_default='0',nullable=False),sa.Column('held_amount',sa.BigInteger(),server_default='0',nullable=False),sa.Column('paid_out_amount',sa.BigInteger(),server_default='0',nullable=False),sa.Column('version',sa.Integer(),server_default='1',nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.UniqueConstraint('partner_id','currency',name='uq_partner_balances_partner_currency'),sa.CheckConstraint('pending_amount >= 0 AND available_amount >= 0 AND held_amount >= 0 AND paid_out_amount >= 0',name='ck_partner_balances_nonnegative'))
 op.create_table('finance_settlements',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('order_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('orders.id',ondelete='RESTRICT'),nullable=False),sa.Column('payment_intent_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('payment_intents.id',ondelete='RESTRICT'),nullable=False),sa.Column('partner_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('partners.id',ondelete='RESTRICT'),nullable=False),sa.Column('customer_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('gross_amount',sa.BigInteger(),nullable=False),sa.Column('commission_bps',sa.Integer(),nullable=False),sa.Column('commission_amount',sa.BigInteger(),nullable=False),sa.Column('net_amount',sa.BigInteger(),nullable=False),sa.Column('refunded_amount',sa.BigInteger(),server_default='0',nullable=False),sa.Column('status',sa.String(30),server_default='pending',nullable=False),sa.Column('available_at',sa.DateTime(timezone=True),nullable=False),sa.Column('released_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.UniqueConstraint('order_id',name='uq_finance_settlements_order'),sa.CheckConstraint('gross_amount >= 0 AND commission_amount >= 0 AND net_amount >= 0 AND refunded_amount >= 0',name='ck_finance_settlements_amounts'))
 op.create_index('ix_finance_settlements_partner_status','finance_settlements',['partner_id','status','available_at'])
 op.create_table('disputes',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('number',sa.String(40),nullable=False,unique=True),sa.Column('order_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('orders.id',ondelete='RESTRICT'),nullable=False),sa.Column('settlement_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('finance_settlements.id',ondelete='RESTRICT'),nullable=False),sa.Column('customer_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('partner_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('partners.id',ondelete='RESTRICT'),nullable=False),sa.Column('opened_by_user_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('resolved_by_user_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('status',sa.String(30),server_default='open',nullable=False),sa.Column('category',sa.String(80),nullable=False),sa.Column('amount',sa.BigInteger(),nullable=False),sa.Column('partner_hold_amount',sa.BigInteger(),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('reason',sa.Text(),nullable=False),sa.Column('resolution_notes',sa.Text()),sa.Column('evidence_due_at',sa.DateTime(timezone=True)),sa.Column('resolved_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.CheckConstraint('amount > 0 AND partner_hold_amount >= 0',name='ck_disputes_amounts'))
 op.create_index('ix_disputes_partner_status','disputes',['partner_id','status'])
 op.create_table('refunds',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('order_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('orders.id',ondelete='RESTRICT'),nullable=False),sa.Column('payment_intent_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('payment_intents.id',ondelete='RESTRICT'),nullable=False),sa.Column('dispute_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('disputes.id',ondelete='SET NULL')),sa.Column('customer_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('partner_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('partners.id',ondelete='RESTRICT'),nullable=False),sa.Column('requested_by_user_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('reviewed_by_user_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('provider',sa.String(50),server_default='mock',nullable=False),sa.Column('provider_reference',sa.String(160)),sa.Column('idempotency_key',sa.String(120),nullable=False,unique=True),sa.Column('amount',sa.BigInteger(),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('status',sa.String(30),server_default='requested',nullable=False),sa.Column('reason',sa.Text(),nullable=False),sa.Column('failure_code',sa.String(120)),sa.Column('requested_at',sa.DateTime(timezone=True),nullable=False),sa.Column('reviewed_at',sa.DateTime(timezone=True)),sa.Column('processed_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.CheckConstraint('amount > 0',name='ck_refunds_amount_positive'))
 op.create_index('ix_refunds_order_status','refunds',['order_id','status'])
 op.create_table('payouts',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('partner_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('partners.id',ondelete='RESTRICT'),nullable=False),sa.Column('requested_by_user_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('reviewed_by_user_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('provider',sa.String(50),server_default='mock',nullable=False),sa.Column('provider_reference',sa.String(160)),sa.Column('idempotency_key',sa.String(120),nullable=False),sa.Column('amount',sa.BigInteger(),nullable=False),sa.Column('fee_amount',sa.BigInteger(),server_default='0',nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('status',sa.String(30),server_default='requested',nullable=False),sa.Column('destination_snapshot',postgresql.JSONB(),nullable=False),sa.Column('failure_code',sa.String(120)),sa.Column('requested_at',sa.DateTime(timezone=True),nullable=False),sa.Column('reviewed_at',sa.DateTime(timezone=True)),sa.Column('processed_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.UniqueConstraint('partner_id','idempotency_key',name='uq_payouts_partner_key'),sa.CheckConstraint('amount > 0 AND fee_amount >= 0',name='ck_payouts_amounts'))
 op.create_index('ix_payouts_partner_status','payouts',['partner_id','status'])
 op.create_table('dispute_evidence',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('dispute_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('disputes.id',ondelete='CASCADE'),nullable=False),sa.Column('uploaded_by_user_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('kind',sa.String(50),nullable=False),sa.Column('storage_key',sa.String(500),nullable=False),sa.Column('sha256',sa.String(64),nullable=False),sa.Column('content_type',sa.String(120),nullable=False),sa.Column('description',sa.Text()),sa.Column('status',sa.String(30),server_default='quarantine',nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.UniqueConstraint('dispute_id','sha256',name='uq_dispute_evidence_hash'))
 op.create_index('ix_dispute_evidence_dispute_created','dispute_evidence',['dispute_id','created_at'])
 op.create_table('reconciliation_runs',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('provider',sa.String(50),nullable=False),sa.Column('period_start',sa.DateTime(timezone=True),nullable=False),sa.Column('period_end',sa.DateTime(timezone=True),nullable=False),sa.Column('status',sa.String(30),server_default='completed',nullable=False),sa.Column('expected_amount',sa.BigInteger(),nullable=False),sa.Column('provider_amount',sa.BigInteger(),nullable=False),sa.Column('variance_amount',sa.BigInteger(),nullable=False),sa.Column('records_checked',sa.Integer(),nullable=False),sa.Column('mismatches',sa.Integer(),nullable=False),sa.Column('report',postgresql.JSONB(),nullable=False),sa.Column('created_by_user_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False))
 op.create_index('ix_reconciliation_provider_period','reconciliation_runs',['provider','period_start','period_end'])
 op.create_table('ledger_transactions',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('reference',sa.String(60),nullable=False,unique=True),sa.Column('transaction_type',sa.String(40),nullable=False),sa.Column('status',sa.String(20),server_default='posted',nullable=False),sa.Column('order_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('orders.id',ondelete='SET NULL')),sa.Column('payment_intent_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('payment_intents.id',ondelete='SET NULL')),sa.Column('refund_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('refunds.id',ondelete='SET NULL')),sa.Column('payout_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('payouts.id',ondelete='SET NULL')),sa.Column('dispute_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('disputes.id',ondelete='SET NULL')),sa.Column('currency',sa.String(3),nullable=False),sa.Column('description',sa.Text(),nullable=False),sa.Column('transaction_metadata',postgresql.JSONB(),nullable=False),sa.Column('posted_at',sa.DateTime(timezone=True),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False))
 op.create_index('ix_ledger_transactions_order_type','ledger_transactions',['order_id','transaction_type'])
 op.create_table('ledger_entries',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('transaction_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('ledger_transactions.id',ondelete='CASCADE'),nullable=False),sa.Column('account_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('ledger_accounts.id',ondelete='RESTRICT'),nullable=False),sa.Column('partner_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('partners.id',ondelete='SET NULL')),sa.Column('direction',sa.String(10),nullable=False),sa.Column('amount',sa.BigInteger(),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.CheckConstraint("direction IN ('debit','credit') AND amount > 0",name='ck_ledger_entries_valid'))
 op.create_index('ix_ledger_entries_transaction','ledger_entries',['transaction_id']);op.create_index('ix_ledger_entries_partner_created','ledger_entries',['partner_id','created_at'])
 for i,c in PERMISSIONS: perm(i,c)
 for r in ('partner_owner','partner_admin'):
  for c in ('finance.balance.read','finance.payout.create','finance.dispute.respond'): grant(r,c)
 for c in ('platform.finance.read','platform.finance.manage','platform.finance.reconcile'): grant('super_admin',c)
 grant('platform_support','platform.finance.read')
 for t in ('partner_balances','finance_settlements','payouts','ledger_entries'): partner_rls(t)
 for t in ('refunds','disputes'): customer_partner_rls(t)
 op.execute(sa.text('ALTER TABLE dispute_evidence ENABLE ROW LEVEL SECURITY'));op.execute(sa.text('ALTER TABLE dispute_evidence FORCE ROW LEVEL SECURITY'));op.execute(sa.text("CREATE POLICY dispute_evidence_scope ON dispute_evidence FOR ALL USING (current_setting('app.is_platform_admin',true)='true' OR EXISTS (SELECT 1 FROM disputes d WHERE d.id=dispute_evidence.dispute_id AND (d.customer_id=NULLIF(current_setting('app.user_id',true),'')::uuid OR EXISTS (SELECT 1 FROM partner_memberships m WHERE m.partner_id=d.partner_id AND m.user_id=NULLIF(current_setting('app.user_id',true),'')::uuid AND m.status='active')))) WITH CHECK (current_setting('app.is_platform_admin',true)='true' OR EXISTS (SELECT 1 FROM disputes d WHERE d.id=dispute_evidence.dispute_id AND (d.customer_id=NULLIF(current_setting('app.user_id',true),'')::uuid OR EXISTS (SELECT 1 FROM partner_memberships m WHERE m.partner_id=d.partner_id AND m.user_id=NULLIF(current_setting('app.user_id',true),'')::uuid AND m.status='active'))))"))
def downgrade():
 for t in ('ledger_entries','ledger_transactions','reconciliation_runs','dispute_evidence','payouts','refunds','disputes','finance_settlements','partner_balances','ledger_accounts'): op.drop_table(t)
 for _,c in reversed(PERMISSIONS): op.execute(sa.text('DELETE FROM permissions WHERE code=:c').bindparams(c=c))
